project:
  type: website
  output-dir: docs

website:
  title: "Paloma Guth Kronbauer"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Maps
        menu:
          - text: US States
            href: us_states_map.qmd
          - text: Wisconsin Districts
            href: wisconsin_district.qmd
      - text: Simulation
        menu: 
          - text: Power analysis
            href: power_test.qmd
      - text: Text Analysis
        menu: 
          - text: News Headlines
            href: text_analysis.qmd
            

page-footer:
    left: |
      &copy; Paloma GUth Kronbauer, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

